FROM openjdk:17

ENV PARAMS="--spring.profiles.active=http"

ARG JAR_FILE=api-monitor-runner/target/api-monitor-runner-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar","/app.jar","$PARAMS"]