api-monitor:
  role: runner
  cache:
    redis:
  communication:
    rest-api:
      enable: true
      orchestrator: "http://localhost:8080"
      register-token: "252fbe30-c2d7-4221-8bad-5d349ab2322e"
    kafka:
      enable:
      ip:
      port:
    redis:
  runner:
    id: f8d16042-897f-4126-9ee3-3f4b24c2857e

