api-monitor:
  role: standalone
  cache:
    redis: true
    expiration: 1800
  communication:
    rest-api:
      enable:
    kafka:
      enable:
      ip:
      port:
    redis:

spring:
  data:
    redis:
      host: localhost

